// Copyright (C) 1991-2009 Altera Corporation
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, Altera MegaCore Function License 
// Agreement, or other applicable license agreement, including, 
// without limitation, that your use is for the sole purpose of 
// programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the 
// applicable agreement for further details.


// Generated by Quartus II 64-Bit Version 9.1 (Build Build 222 10/21/2009)
// Created on Sun May 29 23:00:15 2016

Top_F Top_F_inst
(
	.sysclk(sysclk_sig) ,	// input  sysclk_sig
	.fx(fx_sig) ,	// input  fx_sig
	.sel0(sel0_sig) ,	// input  sel0_sig
	.sel1(sel1_sig) ,	// input  sel1_sig
	.sel2(sel2_sig) ,	// input  sel2_sig
	.data_out(data_out_sig) ,	// output [7:0] data_out_sig
	.interrupt(interrupt_sig) ,	// output  interrupt_sig
	.clk_25mhz(clk_25mhz_sig) 	// output  clk_25mhz_sig
);

